---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-fargate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-fargate
  name: deployment-fargate
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-fargate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-fargate
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.10.1
        imagePullPolicy: Always
        name: app-fargate
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: hello-fargate
  name: service-fargate
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-fargate
