---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-fargate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-fargate
  name: podinfo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podinfo
    spec:
      containers:
      - image: stefanprodan/podinfo
        imagePullPolicy: Always
        name: podinfo
        ports:
        - containerPort: 9898 
---
apiVersion: v1
kind: Service
metadata:
  namespace: hello-fargate
  name: podinfo-service
spec:
  ports:
    - port: 80
      targetPort: 9898
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: podinfo
